name: Release pull request

on:
  release:
    types: [released]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release version
        uses: actions/github-script@v7
        id: version
        with:
          script: |
            const release = context.ref.substring(10)
            const releaseType = release.replace(/^(\d+\.)+\d+-?/, "").replace(/\.\d+$/, "")
            core.setOutput("release", release)
            core.setOutput("releaseType", releaseType || "latest")

      - name: Create release branch
        run: |
          git checkout -B release/${{ steps.version.outputs.release }}
          git push --set-upstream origin release/${{ steps.version.outputs.release }}

      - name: Create pull request
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: release/${{ steps.version.outputs.release }}
          target_branch: main
          title: Release v${{ steps.version.outputs.release }}
          label: release
          body: |
            Merge this PR to release ${{ steps.version.outputs.release }} to production.
