name: Release pull request

on:
  release:
    types: [published]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Get release version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create promotion branch
        run: |
          git checkout -B release/${{ env.VERSION }}
          git push --set-upstream origin release/${{ env.VERSION }}
          git fetch origin develop:develop
          git reset --hard develop

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: release/${{ env.VERSION }}
          title: Release ${{ env.VERSION }}
          body: Merge this PR to release ${{ env.VERSION }} to production
          labels: release
          assignees: benyap
